// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.10.0.0
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------

using PMDEvers.Servicebus;
using Servicebus.Kafka;

namespace WorkerService.Events
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using Avro;
	using Avro.Specific;
	
   [KafkaTopic("Test")]
	public partial class TestEvent : ISpecificRecord, IEvent
	{
		public static Schema _SCHEMA = Avro.Schema.Parse(@"{""type"":""record"",""name"":""TestEvent"",""namespace"":""WorkerService.Events"",""fields"":[{""name"":""Name"",""type"":""string""},{""name"":""FavoriteNumber"",""type"":[""int"",""null""]},{""name"":""FavoriteColor"",""type"":[""string"",""null""]},{""name"":""HourlyRate"",""type"":{""type"":""bytes"",""logicalType"":""decimal"",""precision"":4,""scale"":2}}]}");
		private string _Name;
		private System.Nullable<System.Int32> _FavoriteNumber;
		private string _FavoriteColor;
		private Avro.AvroDecimal _HourlyRate;
		public virtual Schema Schema
		{
			get
			{
				return TestEvent._SCHEMA;
			}
		}
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				this._Name = value;
			}
		}
		public System.Nullable<System.Int32> FavoriteNumber
		{
			get
			{
				return this._FavoriteNumber;
			}
			set
			{
				this._FavoriteNumber = value;
			}
		}
		public string FavoriteColor
		{
			get
			{
				return this._FavoriteColor;
			}
			set
			{
				this._FavoriteColor = value;
			}
		}
		public Avro.AvroDecimal HourlyRate
		{
			get
			{
				return this._HourlyRate;
			}
			set
			{
				this._HourlyRate = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Name;
			case 1: return this.FavoriteNumber;
			case 2: return this.FavoriteColor;
			case 3: return this.HourlyRate;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Name = (System.String)fieldValue; break;
			case 1: this.FavoriteNumber = (System.Nullable<System.Int32>)fieldValue; break;
			case 2: this.FavoriteColor = (System.String)fieldValue; break;
			case 3: this.HourlyRate = (Avro.AvroDecimal)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
